### PR TITLE
Add isSubsetOf method

### PR DESCRIPTION
**Pull request by tdzienniak**
I find this method very handy, so I think it could be a good extension of the lib.

Cheers,
TD

### CODE REVIEW

**Comment by mattkrick** [comment]
Really clean PR, thanks!
Bear with me I'm still not 100% what you mean by subset...
Could you give me an example that meets the following? 
`bs1.isEqual(bs2) === false` and `bs1.isSubsetOf(bs2) === true`?

**Comment by tdzienniak** [comment]
Sure. In pseudo-code:
```
bs1 = 1010
bs2 = 1111
```

In other words:
`bs1 is subset of bs2 <=> bs1 & bs2 equals bs1`

**Comment by mattkrick** [comment]
Gotcha, yeah this would be useful!
Could you make 2 quick changes?
 - Remove the `Math.max`, it's really slow & the spec already mandates that all compared bitsets must have the same number of words, so `arr1.length` will always equal `arr2.length`.
 - change the param name from `bitset` to `bs` in the readme (or change all the other cases from `bs` to `bitset` if you like, but just to keep it all the same).

**Comment by tdzienniak** [comment]
Done.

**Comment by mattkrick** [comment]
Awesome, thanks!

**Comment by tdzienniak** [comment]
Will you merge my PR? I wanted to use your lib in my project using npm package, but now I have to use my fork.

**Comment by mattkrick** [comment]
thanks for the reminder, v1.3.0 should be up on npm

**Comment by jmeas** [comment]
I think you may have forgotten to merge it in for the release, @mattkrick . [Here's the source for v1.3.0](https://github.com/mattkrick/fast-bitset/blob/6d730642ce8ea9db513ba67e87e2f01dede5de5b/app/BitSet.js); there's no subset method there from what I can see.

**Comment by mattkrick** [comment]
gah, i feel like an idiot, guess i didn't merge your changes yesterday. Just got a fresh copy of v1.3.1 off of npm, should be good to go

**Comment by jmeas** [comment]
Happens to the best of us :P

**Pull request merged**
